version: "3"
services:
  backend:
    build: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JaegerAddress=
  graphite:
    image: "graphiteapp/graphite-statsd:latest"
    restart: always
    ports:
      - "80:80"
      - "2003:2003"
      - "2004:2004"
      - "2023:2023"
      - "2024:2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - ./webapp:/webapp